// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AcceptCaregiverLinkReducer from "../accept_caregiver_link_reducer";
import AcknowledgeRecallReducer from "../acknowledge_recall_reducer";
import AddMedicationReducer from "../add_medication_reducer";
import AttachBriefReducer from "../attach_brief_reducer";
import CreateAppointmentReducer from "../create_appointment_reducer";
import CreateProfileReducer from "../create_profile_reducer";
import DeactivateMedicationReducer from "../deactivate_medication_reducer";
import EnqueueScanReducer from "../enqueue_scan_reducer";
import FailScanReducer from "../fail_scan_reducer";
import GenerateDoseScheduleReducer from "../generate_dose_schedule_reducer";
import GrantServiceIdentityReducer from "../grant_service_identity_reducer";
import InviteCaregiverReducer from "../invite_caregiver_reducer";
import LogDoseReducer from "../log_dose_reducer";
import LogSideEffectReducer from "../log_side_effect_reducer";
import RecordInteractionResultReducer from "../record_interaction_result_reducer";
import RecordRecallAlertReducer from "../record_recall_alert_reducer";
import RecordScanResultReducer from "../record_scan_result_reducer";
import RegisterPushSubscriptionReducer from "../register_push_subscription_reducer";
import RemovePushSubscriptionReducer from "../remove_push_subscription_reducer";
import RevokeCaregiverLinkReducer from "../revoke_caregiver_link_reducer";
import SetPgxConsentReducer from "../set_pgx_consent_reducer";
import SetPgxPhenotypesReducer from "../set_pgx_phenotypes_reducer";
import UpdateMedicationReducer from "../update_medication_reducer";
import UpdateProfileReducer from "../update_profile_reducer";

export type AcceptCaregiverLinkParams = __Infer<typeof AcceptCaregiverLinkReducer>;
export type AcknowledgeRecallParams = __Infer<typeof AcknowledgeRecallReducer>;
export type AddMedicationParams = __Infer<typeof AddMedicationReducer>;
export type AttachBriefParams = __Infer<typeof AttachBriefReducer>;
export type CreateAppointmentParams = __Infer<typeof CreateAppointmentReducer>;
export type CreateProfileParams = __Infer<typeof CreateProfileReducer>;
export type DeactivateMedicationParams = __Infer<typeof DeactivateMedicationReducer>;
export type EnqueueScanParams = __Infer<typeof EnqueueScanReducer>;
export type FailScanParams = __Infer<typeof FailScanReducer>;
export type GenerateDoseScheduleParams = __Infer<typeof GenerateDoseScheduleReducer>;
export type GrantServiceIdentityParams = __Infer<typeof GrantServiceIdentityReducer>;
export type InviteCaregiverParams = __Infer<typeof InviteCaregiverReducer>;
export type LogDoseParams = __Infer<typeof LogDoseReducer>;
export type LogSideEffectParams = __Infer<typeof LogSideEffectReducer>;
export type RecordInteractionResultParams = __Infer<typeof RecordInteractionResultReducer>;
export type RecordRecallAlertParams = __Infer<typeof RecordRecallAlertReducer>;
export type RecordScanResultParams = __Infer<typeof RecordScanResultReducer>;
export type RegisterPushSubscriptionParams = __Infer<typeof RegisterPushSubscriptionReducer>;
export type RemovePushSubscriptionParams = __Infer<typeof RemovePushSubscriptionReducer>;
export type RevokeCaregiverLinkParams = __Infer<typeof RevokeCaregiverLinkReducer>;
export type SetPgxConsentParams = __Infer<typeof SetPgxConsentReducer>;
export type SetPgxPhenotypesParams = __Infer<typeof SetPgxPhenotypesReducer>;
export type UpdateMedicationParams = __Infer<typeof UpdateMedicationReducer>;
export type UpdateProfileParams = __Infer<typeof UpdateProfileReducer>;

