// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  owner: __t.identity(),
  name: __t.string(),
  genericName: __t.string(),
  rxnormCode: __t.string(),
  strength: __t.string(),
  form: __t.string(),
  scheduleTimes: __t.array(__t.string()),
  scheduleDays: __t.byteArray(),
  prn: __t.bool(),
  prescriber: __t.string(),
  pharmacy: __t.string(),
  ndc: __t.string(),
  refillDate: __t.timestamp(),
  dosesRemaining: __t.i32(),
  isOtc: __t.bool(),
};
