// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  apptId: __t.u64().primaryKey().name("appt_id"),
  ownerIdentity: __t.identity().name("owner_identity"),
  providerName: __t.string().name("provider_name"),
  providerType: __t.string().name("provider_type"),
  scheduledFor: __t.timestamp().name("scheduled_for"),
  briefRef: __t.string().name("brief_ref"),
  createdAt: __t.timestamp().name("created_at"),
});
