// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  linkId: __t.u64().primaryKey().name("link_id"),
  caregiverIdentity: __t.identity().name("caregiver_identity"),
  patientIdentity: __t.identity().name("patient_identity"),
  caregiverEmail: __t.string().name("caregiver_email"),
  accessLevel: __t.string().name("access_level"),
  status: __t.string(),
  createdAt: __t.timestamp().name("created_at"),
});
