// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  doseId: __t.u64().primaryKey().name("dose_id"),
  medId: __t.u64().name("med_id"),
  ownerIdentity: __t.identity().name("owner_identity"),
  scheduledAt: __t.timestamp().name("scheduled_at"),
  takenAt: __t.option(__t.timestamp()).name("taken_at"),
  status: __t.string(),
  loggedBy: __t.identity().name("logged_by"),
  notes: __t.string(),
});
