// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  medId: __t.u64().primaryKey().name("med_id"),
  ownerIdentity: __t.identity().name("owner_identity"),
  name: __t.string(),
  genericName: __t.string().name("generic_name"),
  rxnormCode: __t.string().name("rxnorm_code"),
  strength: __t.string(),
  form: __t.string(),
  scheduleTimes: __t.array(__t.string()).name("schedule_times"),
  scheduleDays: __t.byteArray().name("schedule_days"),
  prn: __t.bool(),
  prescriber: __t.string(),
  pharmacy: __t.string(),
  ndc: __t.string(),
  refillDate: __t.timestamp().name("refill_date"),
  dosesRemaining: __t.i32().name("doses_remaining"),
  isOtc: __t.bool().name("is_otc"),
  active: __t.bool(),
  lastScanId: __t.u64().name("last_scan_id"),
  createdAt: __t.timestamp().name("created_at"),
});
