// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  identity: __t.identity().primaryKey(),
  fullName: __t.string().name("full_name"),
  dateOfBirth: __t.timestamp().name("date_of_birth"),
  weightKg: __t.f64().name("weight_kg"),
  conditions: __t.array(__t.string()),
  allergies: __t.array(__t.string()),
  pgxPhenotypes: __t.string().name("pgx_phenotypes"),
  pgxConsent: __t.bool().name("pgx_consent"),
  createdAt: __t.timestamp().name("created_at"),
});
