// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  alertId: __t.u64().primaryKey().name("alert_id"),
  ownerIdentity: __t.identity().name("owner_identity"),
  medId: __t.u64().name("med_id"),
  openfdaRecallId: __t.string().name("openfda_recall_id"),
  severity: __t.string(),
  summary: __t.string(),
  acknowledged: __t.bool(),
  createdAt: __t.timestamp().name("created_at"),
});
