// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  scanId: __t.u64().primaryKey().name("scan_id"),
  ownerIdentity: __t.identity().name("owner_identity"),
  imageRef: __t.string().name("image_ref"),
  scanType: __t.string().name("scan_type"),
  identifiedDrug: __t.string().name("identified_drug"),
  identifiedNdc: __t.string().name("identified_ndc"),
  idConfidence: __t.f64().name("id_confidence"),
  authenticity: __t.string(),
  authLayers: __t.string().name("auth_layers"),
  rawAnalysis: __t.string().name("raw_analysis"),
  status: __t.string(),
  createdAt: __t.timestamp().name("created_at"),
});
