// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Appointment = __t.object("Appointment", {
  apptId: __t.u64(),
  ownerIdentity: __t.identity(),
  providerName: __t.string(),
  providerType: __t.string(),
  scheduledFor: __t.timestamp(),
  briefRef: __t.string(),
  createdAt: __t.timestamp(),
});
export type Appointment = __Infer<typeof Appointment>;

export const AuditEntry = __t.object("AuditEntry", {
  entryId: __t.u64(),
  patientIdentity: __t.identity(),
  actorIdentity: __t.identity(),
  action: __t.string(),
  detail: __t.string(),
  at: __t.timestamp(),
});
export type AuditEntry = __Infer<typeof AuditEntry>;

export const CaregiverLink = __t.object("CaregiverLink", {
  linkId: __t.u64(),
  caregiverIdentity: __t.identity(),
  patientIdentity: __t.identity(),
  caregiverEmail: __t.string(),
  accessLevel: __t.string(),
  status: __t.string(),
  createdAt: __t.timestamp(),
});
export type CaregiverLink = __Infer<typeof CaregiverLink>;

export const Dose = __t.object("Dose", {
  doseId: __t.u64(),
  medId: __t.u64(),
  ownerIdentity: __t.identity(),
  scheduledAt: __t.timestamp(),
  takenAt: __t.option(__t.timestamp()),
  status: __t.string(),
  loggedBy: __t.identity(),
  notes: __t.string(),
});
export type Dose = __Infer<typeof Dose>;

export const DoseHorizonTimer = __t.object("DoseHorizonTimer", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type DoseHorizonTimer = __Infer<typeof DoseHorizonTimer>;

export const InteractionsCache = __t.object("InteractionsCache", {
  cacheId: __t.u64(),
  ownerIdentity: __t.identity(),
  pairs: __t.string(),
  cascades: __t.string(),
  modelVersion: __t.string(),
  kbVersion: __t.string(),
  computedAt: __t.timestamp(),
});
export type InteractionsCache = __Infer<typeof InteractionsCache>;

export const Medication = __t.object("Medication", {
  medId: __t.u64(),
  ownerIdentity: __t.identity(),
  name: __t.string(),
  genericName: __t.string(),
  rxnormCode: __t.string(),
  strength: __t.string(),
  form: __t.string(),
  scheduleTimes: __t.array(__t.string()),
  scheduleDays: __t.byteArray(),
  prn: __t.bool(),
  prescriber: __t.string(),
  pharmacy: __t.string(),
  ndc: __t.string(),
  refillDate: __t.timestamp(),
  dosesRemaining: __t.i32(),
  isOtc: __t.bool(),
  active: __t.bool(),
  lastScanId: __t.u64(),
  createdAt: __t.timestamp(),
});
export type Medication = __Infer<typeof Medication>;

export const MissedSweepTimer = __t.object("MissedSweepTimer", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type MissedSweepTimer = __Infer<typeof MissedSweepTimer>;

export const Profile = __t.object("Profile", {
  identity: __t.identity(),
  fullName: __t.string(),
  dateOfBirth: __t.timestamp(),
  weightKg: __t.f64(),
  conditions: __t.array(__t.string()),
  allergies: __t.array(__t.string()),
  pgxPhenotypes: __t.string(),
  pgxConsent: __t.bool(),
  createdAt: __t.timestamp(),
});
export type Profile = __Infer<typeof Profile>;

export const PushSubscription = __t.object("PushSubscription", {
  subId: __t.u64(),
  ownerIdentity: __t.identity(),
  endpoint: __t.string(),
  keys: __t.string(),
  platform: __t.string(),
  createdAt: __t.timestamp(),
});
export type PushSubscription = __Infer<typeof PushSubscription>;

export const RecallAlert = __t.object("RecallAlert", {
  alertId: __t.u64(),
  ownerIdentity: __t.identity(),
  medId: __t.u64(),
  openfdaRecallId: __t.string(),
  severity: __t.string(),
  summary: __t.string(),
  acknowledged: __t.bool(),
  createdAt: __t.timestamp(),
});
export type RecallAlert = __Infer<typeof RecallAlert>;

export const Scan = __t.object("Scan", {
  scanId: __t.u64(),
  ownerIdentity: __t.identity(),
  imageRef: __t.string(),
  scanType: __t.string(),
  identifiedDrug: __t.string(),
  identifiedNdc: __t.string(),
  idConfidence: __t.f64(),
  authenticity: __t.string(),
  authLayers: __t.string(),
  rawAnalysis: __t.string(),
  status: __t.string(),
  createdAt: __t.timestamp(),
});
export type Scan = __Infer<typeof Scan>;

export const ServiceIdentity = __t.object("ServiceIdentity", {
  identity: __t.identity(),
  label: __t.string(),
  grantedAt: __t.timestamp(),
});
export type ServiceIdentity = __Infer<typeof ServiceIdentity>;

export const SideEffect = __t.object("SideEffect", {
  effectId: __t.u64(),
  ownerIdentity: __t.identity(),
  medId: __t.option(__t.u64()),
  symptom: __t.string(),
  severity: __t.u8(),
  loggedAt: __t.timestamp(),
});
export type SideEffect = __Infer<typeof SideEffect>;

